name: first

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: dorny/paths-filter@v2

        id: changes
        with:
          filters: |
            resources:
              - 'resources/**'
            functions:
              - 'functions/**'

      - if: steps.changes.outputs.functions == 'true' && steps.changes.outputs.resources == 'false'
        run: echo funs

      - if: steps.changes.outputs.resources == 'true'
        run: echo reses

      - if: steps.changes.outputs.functions == 'true' || steps.changes.outputs.resources == 'true'
        run: echo functions and resources