name: first

on:
  push:
    branches: 
      - main
    paths:
      - functions/**
      - '!resources/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Echo 1 request
        run: echo ${{ toJson(github) }}
