name: second

on:
  push:
    branches: 
      - main
    paths:
      - resources/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Echo 2 request
        run: echo This is second workflow
